package com.example.spring_demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;

import com.example.spring_demo.entity.plusnumentity;
import com.example.spring_demo.repository.plusnumrepository;

@RestController
public class HomeController {
    
    //基本HelloWorld
    @ResponseBody
    //允許前端去fetch後端資料，所以需要提供LiverServer資訊
    @CrossOrigin(origins = "http://127.0.0.1:5500")

    //Call API
    @GetMapping("/hello")
    public String test() {
        return "HelloWorld";
    }

    //    1 + 1 範例
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private plusnumrepository plusnumrepository;

    // 用来接收来的前端的JSON 数据
    public static class NumberWrapper {
        private Integer number;
        private Integer number2;

        public Integer getNumber() {
            return number;
        }

        public Integer getNumber2() {
            return number2;
        }

        public void setNumber(Integer number) {
            this.number = number;
        }

        public void setNumber2(Integer number2) {
            this.number2 = number2;
        }
    }

    //相加的物件
    public static class PlusNum {
        public Integer Plus(NumberWrapper num) {
            return num.getNumber() + num.getNumber2();
        }
    }

    //實際業務流程API
    @CrossOrigin(origins = "http://127.0.0.1:5500")
    @PostMapping("/receiveNumber")
    public Integer receiveNumber(@RequestBody NumberWrapper numberWrapper) {
        // 印出數字
        System.out.println("Received number1: " + numberWrapper.getNumber());
        System.out.println("Received number2: " + numberWrapper.getNumber2());

        //計算總和
        PlusNum plusnum = new PlusNum();
        Integer result = plusnum.Plus(numberWrapper);
        //印出總和
        System.out.println("TwoSum:" + result);


        //建立Entity並儲存到資料庫
        plusnumentity Plusnumentity = new plusnumentity();
        Plusnumentity.setnumber(numberWrapper.getNumber());
        Plusnumentity.setnumber2(numberWrapper.getNumber2());
        Plusnumentity.setResult(result);

        //儲存到資料庫
        plusnumentity savedEntity = plusnumrepository.save(Plusnumentity);
//        plusnumrepository.save(Plusnumentity);
        System.out.println("Saved entity with ID: " + savedEntity.getId());

        return  result;

    }

}


